services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pdf_backend
    ports:
      - "1000:1000" # Expose for debugging if needed

  frontend:
    build: .        # Build context is the root directory
    container_name: pdf_frontend
    ports:
      - "80:80"     # Access the app at http://localhost
    depends_on:
      - backend